//! Single source of truth for builtin documentation.
//! Consumed by the LSP (hover/completion), the REPL (?func help), and any
//! future doc generators. Generated from the reference tables in CLAUDE.md;
//! keep signatures in sync when builtins change.

pub const Doc = struct {
    name: []const u8,
    signature: []const u8,
    summary: []const u8,
    example: ?[]const u8 = null,
};

pub const docs = [_]Doc{
    .{ .name = "step", .signature = "(step expr)", .summary = "Evaluates expr while printing every reduction with its result (capped at 200 steps)", .example = "(step (fact 3))" },
    .{ .name = "begin", .signature = "(begin e1 e2 ...)", .summary = "Evaluates expressions in order, returning the last", .example = "(begin (print 1) (+ 2 3)) => 5" },
    .{ .name = "cond", .signature = "(cond (test result...) ... (else result...))", .summary = "Multi-branch conditional; else always matches", .example = "(cond ((< x 0) \"neg\") (else \"non-neg\"))" },
    .{ .name = "quote", .signature = "(quote expr) or 'expr", .summary = "Returns expr unevaluated (data, not code)", .example = "'(+ 1 2) => (+ 1 2)" },
    .{ .name = "quasiquote", .signature = "(quasiquote expr) or `expr", .summary = "Like quote, but (unquote x) / ,x evaluates", .example = "`(+ 1 ,(* 2 3)) => (+ 1 6)" },
    .{ .name = "unquote", .signature = "(unquote expr) or ,expr", .summary = "Evaluates expr inside a quasiquote template" },
    .{ .name = "defmacro", .signature = "(defmacro (name params...) template)", .summary = "Defines a macro: params bind to unevaluated arguments, the template builds code", .example = "(defmacro (unless c a b) `(if ,c ,b ,a))" },
    .{ .name = "try", .signature = "(try expr fallback)", .summary = "Evaluates expr; on error evaluates fallback instead", .example = "(try (/ 1 0) \"fallback\") => \"fallback\"" },
    .{ .name = "time", .signature = "(time expr)", .summary = "Evaluates expr and prints the wall-clock time taken" },
    .{ .name = "trace", .signature = "(trace fn-name)", .summary = "Toggles call/return tracing for a user-defined function" },
    .{ .name = "print", .signature = "(print a b ...)", .summary = "Writes arguments separated by spaces, then a newline; strings print raw", .example = "(print \"x =\" 42)" },
    .{ .name = "read", .signature = "(read)", .summary = "Reads one line from input and parses it as an expression; eof at end of input", .example = "(define x (read))" },
    .{ .name = "load", .signature = "(load \"file.lspm\")", .summary = "Evaluates a file in the current environment; returns the statement count" },
    .{ .name = "args", .signature = "(args)", .summary = "Command-line arguments after the script path, as a list of strings" },
    .{ .name = "exit", .signature = "(exit) or (exit code)", .summary = "Terminates the process with an optional status code" },
    .{ .name = "random", .signature = "(random) or (random n)", .summary = "Uniform random float in [0,1), or integer in [0,n)", .example = "(random 6) => 0..5" },
    .{ .name = "random-seed", .signature = "(random-seed n)", .summary = "Seeds the PRNG for reproducible sequences" },
    .{ .name = "sort", .signature = "(sort lst)", .summary = "Ascending sort of numbers, rationals, and strings", .example = "(sort (list 3 1 2)) => (list 1 2 3)" },
    .{ .name = "assoc", .signature = "(assoc key alist)", .summary = "First (key value) pair matching key in a list of pairs, else 0", .example = "(assoc 2 (list (list 1 \"a\") (list 2 \"b\"))) => (list 2 \"b\")" },
    .{ .name = "unit", .signature = "(unit name)", .summary = "One SI or derived unit as a dimension-carrying quantity (m kg s A K mol cd, km cm mm g min h Hz N Pa J W C V)", .example = "(/ (* 100 (unit km)) (unit h)) => 27.78 m/s" },
    .{ .name = "concat", .signature = "(concat s1 s2 ...)", .summary = "Concatenates strings; non-string arguments are rendered", .example = "(concat \"x = \" (+ 1 2)) => \"x = 3\"" },
    .{ .name = "substring", .signature = "(substring s start end)", .summary = "Characters [start, end) of a string", .example = "(substring \"hello world\" 0 5) => \"hello\"" },
    .{ .name = "string->number", .signature = "(string->number s)", .summary = "Parses a number (or p/q rational) from a string", .example = "(string->number \"22/7\") => 22/7" },
    .{ .name = "number->string", .signature = "(number->string x)", .summary = "Renders any expression to its printed form as a string", .example = "(number->string 1/3) => \"1/3\"" },
    .{ .name = "split", .signature = "(split s sep)", .summary = "Splits a string on a separator, returning a list of strings", .example = "(split \"a,b\" \",\") => (list \"a\" \"b\")" },
    .{ .name = "<=", .signature = "(<= a b ...)", .summary = "Chained less-or-equal; symbolic args stay inert" },
    .{ .name = ">=", .signature = "(>= a b ...)", .summary = "Chained greater-or-equal; symbolic args stay inert" },
    .{ .name = "!=", .signature = "(!= a b ...)", .summary = "True when the arguments are not all equal" },
    .{ .name = "read-line", .signature = "(read-line)", .summary = "Reads one raw input line as a string (symbol eof at end)" },
    .{ .name = "string->symbol", .signature = "(string->symbol s)", .summary = "Interns a string as a symbol" },
    .{ .name = "symbol->string", .signature = "(symbol->string sym)", .summary = "The symbol's name as a string" },
    .{ .name = "index-of", .signature = "(index-of s sub)", .summary = "Byte index of the first occurrence of sub in s, or -1" },
    .{ .name = "contains?", .signature = "(contains? s sub)", .summary = "1 when sub occurs in s" },
    .{ .name = "replace", .signature = "(replace s old new)", .summary = "Replaces every occurrence of old with new" },
    .{ .name = "upcase", .signature = "(upcase s)", .summary = "ASCII uppercase copy of s" },
    .{ .name = "downcase", .signature = "(downcase s)", .summary = "ASCII lowercase copy of s" },
    .{ .name = "trim", .signature = "(trim s)", .summary = "Strips leading and trailing whitespace" },
    .{ .name = "char->code", .signature = "(char->code c)", .summary = "Byte value of a 1-character string" },
    .{ .name = "code->char", .signature = "(code->char n)", .summary = "1-character string from a byte value" },
    .{ .name = "read-file", .signature = "(read-file path)", .summary = "Whole file contents as a string (10 MB cap)" },
    .{ .name = "write-file", .signature = "(write-file path s)", .summary = "Writes (replaces) a file with a string; returns 1" },
    .{ .name = "dict", .signature = "(dict k1 v1 k2 v2 ...)", .summary = "Builds a dictionary (string/symbol/int keys); later keys win" },
    .{ .name = "dict-get", .signature = "(dict-get d key) or (dict-get d key default)", .summary = "Lookup; missing keys return the default (or 0)" },
    .{ .name = "dict-has?", .signature = "(dict-has? d key)", .summary = "1 when the key is present" },
    .{ .name = "dict-set", .signature = "(dict-set d key value)", .summary = "A NEW dict with the binding added or replaced" },
    .{ .name = "dict-remove", .signature = "(dict-remove d key)", .summary = "A NEW dict without the key" },
    .{ .name = "dict-keys", .signature = "(dict-keys d)", .summary = "Keys as a list of strings, in insertion order" },
    .{ .name = "dict-values", .signature = "(dict-values d)", .summary = "Values as a list, in insertion order" },
    .{ .name = "dict-size", .signature = "(dict-size d)", .summary = "Number of entries" },
    .{ .name = "dict-merge", .signature = "(dict-merge a b)", .summary = "A NEW dict combining both; b wins on conflicts" },
    .{ .name = "dict?", .signature = "(dict? x)", .summary = "1 when x is a dictionary" },
    .{ .name = "json-parse", .signature = "(json-parse s)", .summary = "JSON text to values (objects->dicts, true/false->1/0, null->'null)" },
    .{ .name = "json-emit", .signature = "(json-emit value)", .summary = "Values to JSON text (dicts->objects, lists->arrays)" },
    .{ .name = "csv-parse", .signature = "(csv-parse s)", .summary = "CSV text to a list of row lists; numeric cells become numbers" },
    .{ .name = "csv-emit", .signature = "(csv-emit rows)", .summary = "A list of row lists to CSV text (quoting as needed)" },
    .{ .name = "now", .signature = "(now)", .summary = "Unix time in seconds (UTC wall clock)" },
    .{ .name = "date-parts", .signature = "(date-parts ts)", .summary = "Dict of year/month/day/hour/minute/second/weekday (UTC)" },
    .{ .name = "date-format", .signature = "(date-format ts)", .summary = "\"YYYY-MM-DD HH:MM:SS\" in UTC" },
    .{ .name = "error-message", .signature = "(error-message)", .summary = "Message of the most recent error, for use in a try fallback" },
    .{ .name = "http-get", .signature = "(http-get url)", .summary = "Fetches a URL: {status body}. Capability port (CLI only)" },
    .{ .name = "exec", .signature = "(exec cmd)", .summary = "Runs a shell command: {status stdout stderr}. Capability port (CLI only)" },
    .{ .name = "zip", .signature = "(zip a b)", .summary = "Prelude: pairs of corresponding elements" },
    .{ .name = "member?", .signature = "(member? xs x)", .summary = "Prelude: 1 when x occurs in xs" },
    .{ .name = "join", .signature = "(join sep xs)", .summary = "Prelude: concatenates strings with a separator" },
    .{ .name = "take", .signature = "(take xs n)", .summary = "Prelude: the first n elements" },
    .{ .name = "drop", .signature = "(drop xs n)", .summary = "Prelude: everything after the first n elements" },
    .{ .name = "flatten", .signature = "(flatten xs)", .summary = "Prelude: nested lists to one flat list" },
    .{ .name = "compose", .signature = "(compose f g)", .summary = "Prelude: the function x -> f(g(x))" },
    .{ .name = "sum-list", .signature = "(sum-list xs)", .summary = "Prelude: sum of a list" },
    .{ .name = "max-by", .signature = "(max-by f xs)", .summary = "Prelude: the element maximizing f" },
    .{ .name = "min-by", .signature = "(min-by f xs)", .summary = "Prelude: the element minimizing f" },
    .{ .name = "numer", .signature = "(numer x)", .summary = "Numerator of an exact rational (integers are n/1)", .example = "(numer 22/7) => 22" },
    .{ .name = "denom", .signature = "(denom x)", .summary = "Denominator of an exact rational (integers are n/1)", .example = "(denom 22/7) => 7" },
    .{ .name = "number?", .signature = "(number? x)", .summary = "True for numbers and exact rationals" },
    .{ .name = "integer?", .signature = "(integer? x)", .summary = "True for integer-valued numbers" },
    .{ .name = "rational?", .signature = "(rational? x)", .summary = "True for exact rationals and integers" },
    .{ .name = "symbol?", .signature = "(symbol? x)", .summary = "True for symbols" },
    .{ .name = "string?", .signature = "(string? x)", .summary = "True for strings" },
    .{ .name = "list?", .signature = "(list? x)", .summary = "True for lists" },
    .{ .name = "lambda?", .signature = "(lambda? x)", .summary = "True for functions" },
    .{ .name = "null?", .signature = "(null? x)", .summary = "True for the empty list" },
    .{ .name = "complex?", .signature = "(complex? x)", .summary = "True for complex numbers" },
    .{ .name = "apply", .signature = "(apply f arg-list)", .summary = "Calls f with the elements of arg-list as arguments", .example = "(apply + '(1 2 3)) => 6" },
    .{ .name = "error", .signature = "(error \"message\" ...)", .summary = "Raises a user error, printing the message" },
    .{ .name = "assert", .signature = "(assert cond [\"message\"])", .summary = "Errors when cond is false; the test runner counts failures", .example = "(assert (= (+ 1 1) 2) \"arithmetic works\")" },
    .{ .name = "define", .signature = "(define name value) or (define (name params...) body)", .summary = "Binds a value, or defines a function (captures free variables by value)", .example = "(define (square x) (* x x))" },
    .{ .name = "lambda", .signature = "(lambda (params...) body)", .summary = "Creates an anonymous function (closure)", .example = "((lambda (x) (* x x)) 5) => 25" },
    .{ .name = "let", .signature = "(let ((var val) ...) body)", .summary = "Local bindings with lexical scope", .example = "(let ((a 3) (b 4)) (+ a b)) => 7" },
    .{ .name = "letrec", .signature = "(letrec ((var val) ...) body)", .summary = "Recursive local bindings (functions can call themselves)", .example = "(letrec ((f (lambda (n) (if (= n 0) 1 (* n (f (- n 1))))))) (f 5)) => 120" },
    .{ .name = "if", .signature = "(if condition then-expr [else-expr])", .summary = "Conditional; stays symbolic when the condition is undecidable", .example = "(if (> 2 1) \"yes\" \"no\")" },
    .{ .name = "sum", .signature = "(sum var start end body)", .summary = "Summation of body for var from start to end", .example = "(sum i 1 5 (* i i)) => 55" },
    .{ .name = "product", .signature = "(product var start end body)", .summary = "Product of body for var from start to end", .example = "(product i 1 5 i) => 120" },
    .{ .name = "+", .signature = "(+ a b c ...)", .summary = "Addition (variadic; complex, vectors, matrices)" },
    .{ .name = "-", .signature = "(- a b ...) or (- a)", .summary = "Subtraction; unary form negates" },
    .{ .name = "*", .signature = "(* a b c ...)", .summary = "Multiplication (variadic; complex, scalar·vector/matrix)" },
    .{ .name = "/", .signature = "(/ a b) or (/ a)", .summary = "Division; unary form is the reciprocal" },
    .{ .name = "^", .signature = "(^ base exp)", .summary = "Exponentiation (complex base; negative base with fractional exponent gives the principal complex value)" },
    .{ .name = "pow", .signature = "(^ base exp)", .summary = "Exponentiation (complex base; negative base with fractional exponent gives the principal complex value)" },
    .{ .name = "abs", .signature = "(abs x)", .summary = "Absolute value (magnitude for complex)" },
    .{ .name = "floor", .signature = "(floor x)", .summary = "Round down" },
    .{ .name = "ceil", .signature = "(ceil x)", .summary = "Round up" },
    .{ .name = "round", .signature = "(round x)", .summary = "Round to nearest" },
    .{ .name = "sign", .signature = "(sign x)", .summary = "-1, 0, or 1" },
    .{ .name = "simplify", .signature = "(simplify expr)", .summary = "Algebraic simplification", .example = "(simplify (+ x x)) => (* 2 x)" },
    .{ .name = "evalf", .signature = "(evalf expr) or (N expr)", .summary = "Numeric evaluation of constants (pi, e)" },
    .{ .name = "N", .signature = "(evalf expr) or (N expr)", .summary = "Numeric evaluation of constants (pi, e)" },
    .{ .name = "diff", .signature = "(diff expr var) or (diff expr var n)", .summary = "Differentiation (nth derivative)", .example = "(diff (^ x 3) x) => (* 3 (^ x 2))" },
    .{ .name = "integrate", .signature = "(integrate expr var) or (integrate expr var a b)", .summary = "Integration (indefinite or definite)" },
    .{ .name = "expand", .signature = "(expand expr)", .summary = "Expand products", .example = "(expand (^ (+ x 1) 2)) => (+ (^ x 2) (* 2 x) 1)" },
    .{ .name = "substitute", .signature = "(substitute expr var value)", .summary = "Variable substitution", .example = "(substitute (+ x y) x 3) => (+ 3 y)" },
    .{ .name = "taylor", .signature = "(taylor expr var point order)", .summary = "Taylor series expansion", .example = "(taylor (exp x) x 0 4) => (+ 1 x (/ (^ x 2) 2) ...)" },
    .{ .name = "solve", .signature = "(solve expr var) or (solve (= left right) var)", .summary = "Solve equation (linear/quadratic)", .example = "(solve (+ (^ x 2) (* -4 1)) x) => (solutions 2 -2)" },
    .{ .name = "factor", .signature = "(factor expr var)", .summary = "Factor polynomial", .example = "(factor (+ (^ x 2) (* -1 1)) x) => (* (- x 1) (+ x 1))" },
    .{ .name = "partial-fractions", .signature = "(partial-fractions expr var)", .summary = "Partial fraction decomposition" },
    .{ .name = "collect", .signature = "(collect expr var)", .summary = "Collect like terms", .example = "(collect (+ (* 2 x) (* 3 x) 5) x) => (+ (* 5 x) 5)" },
    .{ .name = "limit", .signature = "(limit expr var point)", .summary = "Limit with L'Hôpital's rule", .example = "(limit (/ (sin x) x) x 0) => 1" },
    .{ .name = "sin", .signature = "(sin x)", .summary = "Sine" },
    .{ .name = "cos", .signature = "(cos x)", .summary = "Cosine" },
    .{ .name = "tan", .signature = "(tan x)", .summary = "Tangent" },
    .{ .name = "asin", .signature = "(asin x)", .summary = "Arc sine" },
    .{ .name = "acos", .signature = "(acos x)", .summary = "Arc cosine" },
    .{ .name = "atan", .signature = "(atan x)", .summary = "Arc tangent" },
    .{ .name = "atan2", .signature = "(atan2 y x)", .summary = "Two-argument arc tangent" },
    .{ .name = "sinh", .signature = "(sinh x)", .summary = "Hyperbolic sine" },
    .{ .name = "cosh", .signature = "(cosh x)", .summary = "Hyperbolic cosine" },
    .{ .name = "tanh", .signature = "(tanh x)", .summary = "Hyperbolic tangent" },
    .{ .name = "asinh", .signature = "(asinh x)", .summary = "Inverse hyperbolic sine" },
    .{ .name = "acosh", .signature = "(acosh x)", .summary = "Inverse hyperbolic cosine" },
    .{ .name = "atanh", .signature = "(atanh x)", .summary = "Inverse hyperbolic tangent" },
    .{ .name = "exp", .signature = "(exp x)", .summary = "Exponential (e^x)" },
    .{ .name = "ln", .signature = "(ln x)", .summary = "Natural logarithm" },
    .{ .name = "log", .signature = "(log x) or (log x base)", .summary = "Logarithm of x (default base 10)", .example = "(log 100 10) => 2" },
    .{ .name = "sqrt", .signature = "(sqrt x)", .summary = "Square root; (sqrt -4) => (complex 0 2)" },
    .{ .name = "complex", .signature = "(complex re im)", .summary = "Create complex number", .example = "(complex 3 4) => 3 + 4i" },
    .{ .name = "real", .signature = "(real z)", .summary = "Real part" },
    .{ .name = "imag", .signature = "(imag z)", .summary = "Imaginary part" },
    .{ .name = "conj", .signature = "(conj z)", .summary = "Complex conjugate" },
    .{ .name = "magnitude", .signature = "(magnitude z)", .summary = "Absolute value" },
    .{ .name = "arg", .signature = "(arg z)", .summary = "Argument (angle)" },
    .{ .name = "rule", .signature = "(rule pattern replacement)", .summary = "Define rewrite rule", .example = "(rule (double ?x) (* 2 ?x))" },
    .{ .name = "rewrite", .signature = "(rewrite expr)", .summary = "Apply all defined rules" },
    .{ .name = "matrix", .signature = "(matrix (r1) (r2) ...)", .summary = "Create matrix", .example = "(matrix (1 2) (3 4)) => 2x2 matrix" },
    .{ .name = "det", .signature = "(det M)", .summary = "Determinant" },
    .{ .name = "transpose", .signature = "(transpose M)", .summary = "Transpose" },
    .{ .name = "trace", .signature = "(trace M)", .summary = "Trace (sum of diagonal)" },
    .{ .name = "matmul", .signature = "(matmul A B)", .summary = "Matrix multiplication" },
    .{ .name = "inv", .signature = "(inv M)", .summary = "Matrix inverse" },
    .{ .name = "eigenvalues", .signature = "(eigenvalues M)", .summary = "Eigenvalues (2x2 only)" },
    .{ .name = "eigenvectors", .signature = "(eigenvectors M)", .summary = "Eigenvectors (2x2 only)" },
    .{ .name = "linsolve", .signature = "(linsolve A b)", .summary = "Solve linear system Ax=b" },
    .{ .name = "lu", .signature = "(lu M)", .summary = "LU decomposition" },
    .{ .name = "charpoly", .signature = "(charpoly M var)", .summary = "Characteristic polynomial" },
    .{ .name = "vector", .signature = "(vector x y z ...)", .summary = "Create vector", .example = "(vector 1 2 3) => ⟨1, 2, 3⟩" },
    .{ .name = "dot", .signature = "(dot v1 v2)", .summary = "Dot product" },
    .{ .name = "cross", .signature = "(cross v1 v2)", .summary = "Cross product (3D only)" },
    .{ .name = "norm", .signature = "(norm v)", .summary = "Euclidean norm" },
    .{ .name = "gradient", .signature = "(gradient f vars)", .summary = "Gradient of scalar field" },
    .{ .name = "grad", .signature = "(gradient f vars)", .summary = "Gradient of scalar field", .example = "(gradient (+ (^ x 2) (^ y 2)) (vector x y))" },
    .{ .name = "divergence", .signature = "(divergence F vars)", .summary = "Divergence of vector field" },
    .{ .name = "curl", .signature = "(curl F vars)", .summary = "Curl of vector field (3D)" },
    .{ .name = "laplacian", .signature = "(laplacian f vars)", .summary = "Laplacian of scalar field" },
    .{ .name = "and", .signature = "(and a b ...)", .summary = "Logical AND (variadic)" },
    .{ .name = "or", .signature = "(or a b ...)", .summary = "Logical OR (variadic)" },
    .{ .name = "not", .signature = "(not a)", .summary = "Logical NOT" },
    .{ .name = "xor", .signature = "(xor a b)", .summary = "Exclusive OR" },
    .{ .name = "implies", .signature = "(implies a b)", .summary = "Logical implication" },
    .{ .name = "mod", .signature = "(mod a b)", .summary = "Modulo" },
    .{ .name = "gcd", .signature = "(gcd a b)", .summary = "Greatest common divisor" },
    .{ .name = "lcm", .signature = "(lcm a b)", .summary = "Least common multiple" },
    .{ .name = "modpow", .signature = "(modpow base exp mod)", .summary = "Modular exponentiation" },
    .{ .name = "prime?", .signature = "(prime? n)", .summary = "Primality test" },
    .{ .name = "factorize", .signature = "(factorize n)", .summary = "Prime factorization" },
    .{ .name = "totient", .signature = "(totient n)", .summary = "Euler's totient function" },
    .{ .name = "extgcd", .signature = "(extgcd a b)", .summary = "Extended GCD (Bezout coefficients)" },
    .{ .name = "crt", .signature = "(crt (vector r1 r2 ...) (vector m1 m2 ...))", .summary = "Chinese Remainder Theorem" },
    .{ .name = "factorial", .signature = "(factorial n) or (! n)", .summary = "Factorial (exact arbitrary precision above 20!)" },
    .{ .name = "!", .signature = "(factorial n) or (! n)", .summary = "Factorial (exact arbitrary precision above 20!)" },
    .{ .name = "binomial", .signature = "(binomial n k)", .summary = "Binomial coefficient" },
    .{ .name = "choose", .signature = "(binomial n k)", .summary = "Binomial coefficient" },
    .{ .name = "permutations", .signature = "(permutations n r)", .summary = "P(n,r); errors when r > n" },
    .{ .name = "combinations", .signature = "(combinations n r)", .summary = "C(n,r)" },
    .{ .name = "mean", .signature = "(mean x1 x2 ...)", .summary = "Arithmetic mean" },
    .{ .name = "variance", .signature = "(variance x1 x2 ...)", .summary = "Population variance" },
    .{ .name = "stddev", .signature = "(stddev x1 x2 ...)", .summary = "Standard deviation" },
    .{ .name = "median", .signature = "(median x1 x2 ...)", .summary = "Median" },
    .{ .name = "min", .signature = "(min x1 x2 ...)", .summary = "Minimum" },
    .{ .name = "max", .signature = "(max x1 x2 ...)", .summary = "Maximum" },
    .{ .name = "coeffs", .signature = "(coeffs a b c ...)", .summary = "Create coefficient list" },
    .{ .name = "polydiv", .signature = "(polydiv (coeffs ...) (coeffs ...) var)", .summary = "Polynomial division (coefficient lists)" },
    .{ .name = "polygcd", .signature = "(polygcd p1 p2)", .summary = "Polynomial GCD" },
    .{ .name = "polylcm", .signature = "(polylcm p1 p2)", .summary = "Polynomial LCM" },
    .{ .name = "roots", .signature = "(roots expr var)", .summary = "Find polynomial roots" },
    .{ .name = "discriminant", .signature = "(discriminant expr var)", .summary = "Discriminant" },
    .{ .name = "assume", .signature = "(assume var property)", .summary = "Set assumption" },
    .{ .name = "is?", .signature = "(is? var property)", .summary = "Check assumption" },
    .{ .name = "=", .signature = "(= a b ...)", .summary = "Equality (variadic; returns 1 or 0)" },
    .{ .name = "<", .signature = "(< a b ...)", .summary = "Chained less-than; symbolic args stay inert" },
    .{ .name = ">", .signature = "(> a b ...)", .summary = "Chained greater-than; symbolic args stay inert" },
    .{ .name = "gamma", .signature = "(gamma x)", .summary = "Gamma function Γ(x)" },
    .{ .name = "beta", .signature = "(beta a b)", .summary = "Beta function B(a,b)" },
    .{ .name = "erf", .signature = "(erf x)", .summary = "Error function" },
    .{ .name = "erfc", .signature = "(erfc x)", .summary = "Complementary error function" },
    .{ .name = "besselj", .signature = "(besselj n x)", .summary = "Bessel function of first kind J_n(x)" },
    .{ .name = "bessely", .signature = "(bessely n x)", .summary = "Bessel function of second kind Y_n(x)" },
    .{ .name = "digamma", .signature = "(digamma x)", .summary = "Digamma function ψ(x)" },
    .{ .name = "dsolve", .signature = "(dsolve (= (diff y x) rhs) y x)", .summary = "Solve first-order ODE (special form: the equation is not pre-evaluated)" },
    .{ .name = "fourier", .signature = "(fourier expr x n)", .summary = "Fourier series: returns (fourier-series a0 ((a1 b1) ... (an bn))) with numerically computed (noise-snapped) coefficients" },
    .{ .name = "laplace", .signature = "(laplace expr t s)", .summary = "Laplace transform" },
    .{ .name = "inv-laplace", .signature = "(inv-laplace expr s t)", .summary = "Inverse Laplace transform" },
    .{ .name = "tensor", .signature = "(tensor data)", .summary = "Create tensor" },
    .{ .name = "tensor-rank", .signature = "(tensor-rank T)", .summary = "Get tensor rank" },
    .{ .name = "tensor-contract", .signature = "(tensor-contract T i j)", .summary = "Contract indices" },
    .{ .name = "tensor-product", .signature = "(tensor-product T1 T2)", .summary = "Outer product" },
    .{ .name = "lagrange", .signature = "(lagrange (list (vector x y) ...) var)", .summary = "Lagrange interpolation" },
    .{ .name = "newton-interp", .signature = "(newton-interp (list (vector x y) ...) var)", .summary = "Newton interpolation" },
    .{ .name = "newton-raphson", .signature = "(newton-raphson expr var x0 tol)", .summary = "Newton-Raphson method" },
    .{ .name = "bisection", .signature = "(bisection expr var a b tol)", .summary = "Bisection method" },
    .{ .name = "to-cf", .signature = "(to-cf x)", .summary = "Convert to continued fraction" },
    .{ .name = "from-cf", .signature = "(from-cf cf)", .summary = "Convert from continued fraction" },
    .{ .name = "cf-convergent", .signature = "(cf-convergent cf n)", .summary = "Get nth convergent" },
    .{ .name = "cf-rational", .signature = "(cf-rational p q)", .summary = "CF from rational p/q" },
    .{ .name = "car", .signature = "(car lst)", .summary = "First element" },
    .{ .name = "cdr", .signature = "(cdr lst)", .summary = "Rest of list" },
    .{ .name = "cons", .signature = "(cons x lst)", .summary = "Prepend element" },
    .{ .name = "list", .signature = "(list a b c ...)", .summary = "Create list" },
    .{ .name = "length", .signature = "(length lst)", .summary = "List length" },
    .{ .name = "nth", .signature = "(nth lst n)", .summary = "Get nth element" },
    .{ .name = "map", .signature = "(map fn lst)", .summary = "Map function over list", .example = "(map (lambda (x) (* x 2)) (list 1 2 3))" },
    .{ .name = "filter", .signature = "(filter fn lst)", .summary = "Filter list by predicate" },
    .{ .name = "reduce", .signature = "(reduce fn init lst)", .summary = "Reduce list" },
    .{ .name = "append", .signature = "(append lst1 lst2)", .summary = "Concatenate lists" },
    .{ .name = "reverse", .signature = "(reverse lst)", .summary = "Reverse list" },
    .{ .name = "range", .signature = "(range n) or (range start end) or (range start end step)", .summary = "Generate range" },
    .{ .name = "memoize", .signature = "(memoize expr)", .summary = "Cache expression result" },
    .{ .name = "memo-clear", .signature = "(memo-clear)", .summary = "Clear memoization cache" },
    .{ .name = "memo-stats", .signature = "(memo-stats)", .summary = "Get cache size" },
    .{ .name = "plot-ascii", .signature = "(plot-ascii expr xmin xmax) or (plot-ascii expr xmin xmax height width)", .summary = "ASCII plot" },
    .{ .name = "plot-svg", .signature = "(plot-svg expr xmin xmax) or (plot-svg expr xmin xmax height width)", .summary = "SVG plot" },
    .{ .name = "plot-points", .signature = "(plot-points points)", .summary = "Plot discrete points" },
    .{ .name = "diff-steps", .signature = "(diff-steps expr var)", .summary = "Differentiation with steps" },
    .{ .name = "integrate-steps", .signature = "(integrate-steps expr var)", .summary = "Integration with steps" },
    .{ .name = "simplify-steps", .signature = "(simplify-steps expr)", .summary = "Simplification with steps" },
    .{ .name = "solve-steps", .signature = "(solve-steps expr var)", .summary = "Equation solving with steps" },
    .{ .name = "quat", .signature = "(quat w x y z)", .summary = "Create quaternion w + xi + yj + zk" },
    .{ .name = "quat+", .signature = "(quat+ q1 q2)", .summary = "Quaternion addition" },
    .{ .name = "quat*", .signature = "(quat* q1 q2)", .summary = "Hamilton product" },
    .{ .name = "quat-conj", .signature = "(quat-conj q)", .summary = "Conjugate" },
    .{ .name = "quat-norm", .signature = "(quat-norm q)", .summary = "Norm (magnitude)" },
    .{ .name = "quat-inv", .signature = "(quat-inv q)", .summary = "Multiplicative inverse" },
    .{ .name = "quat-scalar", .signature = "(quat-scalar q)", .summary = "Scalar part (w)" },
    .{ .name = "quat-vector", .signature = "(quat-vector q)", .summary = "Vector part (x, y, z)" },
    .{ .name = "gf", .signature = "(gf value prime)", .summary = "Create element in GF(p); p must be prime" },
    .{ .name = "gf+", .signature = "(gf+ a b)", .summary = "Addition in GF(p)" },
    .{ .name = "gf-", .signature = "(gf- a b)", .summary = "Subtraction in GF(p)" },
    .{ .name = "gf*", .signature = "(gf* a b)", .summary = "Multiplication in GF(p)" },
    .{ .name = "gf/", .signature = "(gf/ a b)", .summary = "Division in GF(p)" },
    .{ .name = "gf^", .signature = "(gf^ a n)", .summary = "Exponentiation in GF(p)" },
    .{ .name = "gf-inv", .signature = "(gf-inv a)", .summary = "Multiplicative inverse" },
    .{ .name = "gf-neg", .signature = "(gf-neg a)", .summary = "Negation" },
    .{ .name = "latex", .signature = "(latex expr)", .summary = "Convert to LaTeX string" },
};

const std = @import("std");

/// Looks up documentation for a builtin or special form by name.
pub fn find(name: []const u8) ?Doc {
    for (docs) |doc| {
        if (std.mem.eql(u8, doc.name, name)) return doc;
    }
    return null;
}
